code/extensions/LeftAndMainSubsites.php

previously if you were editing settings and you changed subsites ti would revert you to /admin, now it stays within your current controller

redirect_fix_between_CMS_sections

---

code/extensions/LeftAndMainSubsites.php

This is early enough in the script that the correct subsite will be used from hereon.
The current subsite is also set prior to redirects based on the URL so the correct subsite is always set for the current page.
@pitchandtone this is on top of your fix. If you could find the time to double check it doesn't break what you fixed that would be much appreciated :+1:

FIX: Removed unnecessary redirect. 

---

.travis.yml
code/extensions/FileSubsites.php
code/extensions/GroupSubsites.php
code/extensions/SiteConfigSubsites.php
code/extensions/SiteTreeSubsites.php
composer.json
tests/behat/features/bootstrap/Context/FeatureContext.php

Part of the 3.2 API was reverted to better support backwards compatibility with 3.1 modules.

Use 3.2 compatible API

---

tests/SiteTreeSubsitesTest.php

See http://www.silverstripe.org/software/download/security-releases/ss-2015-008-sitetree-creation-permission-vulnerability
Logged out users can never create pages (fixed in cms)
CMSMain controls pages creatable at the root using SiteTreeHints, as the PageTypes no longer assumes knowledge of the ability to create pages.

Fix subsites to use correct permissions

---

css/LeftAndMain_Subsites.css

The SubsitesVirtualPage icon is hidden in the CMS when using the subsite module and CWP

SubsitesVirtualPage icon disapears in CMS

---

templates/LeftAndMain_Menu.ss

Added the button down the bottom of the main CMS menu to toggle the 'sticky' state of the menu

Add sticky nav toggle button

---

templates/LeftAndMain_Menu.ss

Synchronises this module with the upstream framework template.
I've also created https://github.com/silverstripe/silverstripe-framework/pull/4795 to help minimise the impact of these kinds of issues in future, but neither depends on the other. (you can merge one or the other safely without regression).

BUG Fix menu compatibility with framework 4.x

---

code/model/Subsite.php

This PR fixed unable to create subsite problem.
I was unable to create a subsite, because of no themes been shown in Theme dropdown menu.
How to test:
1> Use composer to install a fresh copy of Silverstripe 3.2
2> Use composer to install subsite module.
3> Try to create a subsite. 
4> No themes loaded into Theme dropdown menu.
5> Apply this PR.
6> fresh page / or dev/build,  now, themes loaded into The dropdown menu.

Subsite module does not picks up themes

---

templates/LeftAndMain_Menu.ss

This fixes issues in the menu which cause the logout icon to appear incorrectly.
I've tested that this works in 3.2 as well.

Update templates for 3.3 compatibility

---

templates/LeftAndMain_Menu.ss

Fix for missing attributes defined in CMSMenu::add_link($id, $title,
$link, $priority, $attributes);

Added attributes to menu link

---

code/SubsitesVirtualPage.php
code/extensions/SiteTreeSubsites.php
code/model/Subsite.php
tests/BaseSubsiteTest.php
tests/SiteTreeSubsitesTest.php
tests/SubsiteTest.php
tests/SubsiteTest.yml
tests/SubsitesVirtualPageTest.php

With this fix in place, validateURLSegment() will no longer check for conflicts against pages that belong to other subsites.
I've also removed the custom logic from SubsiteVirtualPage: It didn't work properly, and the substituted logic should work better. :) This is covered by existing tests.
Fixes #193 and #53 
The code in this module is super-due for a rewrite soon.

BUG Fix issue with urlsegment being renamed in subsites

---

code/SubsiteXHRController.php
tests/SubsiteXHRControllerTest.php

Fixes #200
The problem is that, even if there are no subsites available, that doesn't mean you're not allowed to know there are no subsites. :)  This replaces the logic check with an actual permission check.
Jira ticket at https://silverstripe.atlassian.net/browse/CWP-697

BUG Prevent SubsiteXHRController failing if there are no subsites available

---

code/extensions/SiteTreeSubsites.php

Credit to @mparkhill who fixed this originally, but never raised a pull request to get the fix back to the base module.

Fix error when dataQuery is a null object

---

tests/FileSubsitesTest.php
tests/SiteTreeSubsitesTest.php
tests/SubsitesVirtualPageTest.php

Some environmental issues arise when testing in a non-root folder, or with the translatable module installed. This simply ensures that these don't interfere with subsites-specific tests.

BUG Prevent translatable / subdirs interfering with test state

---

code/model/Subsite.php

Avoids errors when a column named MemberID has been added to Group or Member via an extension.

Update SQL to remove ambiguity

---

code/model/Subsite.php

Adjusting a query used in getSubsiteIDForDomain to prevent new DB fields being added to the SQL call if they are not yet added to the DB.
Context:
We have an extension in our project that adds a DB field to `Subsite`. We also have a module in our project (akismet) that triggers `Translatable->populateSiteConfigDefaults()`, which ends up triggering `Subsite::currentSubsiteID()` before our extension has been applied. This eventually ends up in calling the `Subsite->getSubsiteIDForDomain()` method and at the adjusted line of code, it creates a SQL query that references the new field which does not exist, so we cannot complete a `dev/build`.

Adjusting query used in getSubsiteIDForDomain

---

_config.php
_config/middleware.yml
code/Middleware/InitStateMiddleware.php
code/State/SubsiteState.php
code/extensions/CMSPageAddControllerExtension.php
code/extensions/FileSubsites.php
code/extensions/GroupSubsites.php
code/extensions/LeftAndMainSubsites.php
code/extensions/SiteConfigSubsites.php
code/extensions/SiteTreeSubsites.php
code/model/Subsite.php
tests/php/LeftAndMainSubsitesTest.php
tests/php/SiteTreeSubsitesTest.php
tests/php/SubsiteAdminFunctionalTest.php
tests/php/SubsiteFunctionalTest.php
tests/php/SubsiteTest.php

This adds a SubsiteState service which contains the subsite ID and can be accessed globally, adds detection via a middleware and replaces `Subsite::currentSubsiteID` use with it.
Added deprecation version and notice to `Subsite::currentSubsiteID`.

NEW Add SubsiteState and initialisation middleware

---

code/Middleware/InitStateMiddleware.php

When a database exception is caught in middleware (database is not ready yet) we need to ensure that the next request (delegate) is returned to keep the request flow going, otherwise we get this on dev/build when first installing the module:
```
Fatal error: Call to a member function output() on null in /Users/robbieaverill/dev/ss4/framework/cli-script.php on line 23
Call Stack:
0.0001     230808   1. {main}() /Users/robbieaverill/dev/ss4/framework/cli-script.php:0
ERROR [Alert]: Call to a member function output() on null
IN GET dev/build
Line 23 in /Users/robbieaverill/dev/ss4/framework/cli-script.php
Source
======
14:  }
15:  
16:  // Build request and detect flush
17:  $request = CLIRequestBuilder::createFromEnvironment();
18:  
19:  // Default application
20:  $kernel = new …
```

FIX Ensure delegated requests are continued when DB builds fail in middleware

---

.upgrade.yml
lang/ar.yml
lang/cs.yml
lang/de.yml
lang/en.yml
lang/eo.yml
lang/fa_IR.yml
lang/fi.yml
lang/hr.yml
lang/id.yml
lang/ja.yml
lang/lt.yml
lang/mi.yml
lang/nb_NO.yml
lang/nl.yml
lang/pl_PL.yml
lang/ru.yml
lang/tr_TR.yml
lang/zh.yml
src/Extension/FileSubsites.php
src/Extension/GroupSubsites.php
src/Extension/LeftAndMainSubsites.php
src/Extension/SiteTreeSubsites.php
src/Forms/GridFieldSubsiteDetailForm.php
src/Model/Subsite.php
src/Model/SubsiteDomain.php
src/Pages/SubsitesVirtualPage.php
src/Reports/SubsiteReportWrapper.php

Issue #290
@tractorcow do we need to freeze or fork translations for Subsites 3.x compatibility?

NEW Namespace translations, implement into class localisation calls

---

javascript/LeftAndMain_Subsites.js
lang/en.yml
src/Model/Subsite.php

This pull request does:
* Use default scaffolding for getCMSFields on Subsite class
* Remove previously not shown tabs and form fields due to default scaffolding
* Re-arrange CMS fields for UX consistency
* Move Domains GridField in Subsite CMS fields into its own tab
* Fix the PJAX fragment reloading for the subsite list in the CMS when certain actions (e.g. adding a subsite) are performed
* Moves Subsite's private statics to the top of the class (from the middle) so they're with their brothers and sisters

FIX Update XHR controller hook selector and refactor getCMSFields to use scaffolding and separate tabs

---

lang/en.yml
src/Model/Subsite.php

Request from @sachajudd after discussion with @clarkepaul : "Can you please in the tab domains remove the heading "Domains" and also change the "Main" tab back to configuration and remove the heading "Subsite configuration"

NEW Remove Subsite Configuration header, rename Main tab and remove Domains GridField title

---

.travis.yml
behat.yml
phpunit.xml.dist

Behat is failing, I don't have much time to investigate it right now so I've added it to allowed failures. I think we should revisit once beta4 is released.

FIX Use vendor file paths for CI references to core

---

src/Model/Subsite.php

will enable `canEdit()` to return something other than true

Subsite - allow canEdit to be extended

---

.travis.yml
CHANGELOG.md
src/Extensions/FileSubsites.php
src/Model/Subsite.php
tests/php/BaseSubsiteTest.php
tests/php/FileSubsitesTest.php
tests/php/SubsiteAdminTest.php
tests/php/SubsiteTest.php
tests/php/SubsitesVirtualPageTest.php

I've left `Subsite::$force_subsite` as a public static but deprecated it in favour of using the SubsiteState instead, and have also left `$disable_subsite_filter` the way it is because it's used in a few other modules (including the CMS). Ideally in the next major release this will become part of the SubsiteState as well.
Resolves #174

API Convert most of Subsite public statics to config properties

---

javascript/SubsitesTreeDropdownField.js
src/Extensions/LeftAndMainSubsites.php
src/Extensions/SiteTreeSubsites.php
src/Forms/SubsitesTreeDropdownField.php
src/Pages/SubsitesVirtualPage.php

This PR fixes the redirection to edit a page from another subsite, and the SubsitesTreeDropdownField
implementation and Javascript API points to refresh the tree when changing the source subsite in
the dropdown of a virtual page.
Requires https://github.com/silverstripe/silverstripe-admin/pull/414
Fixes #298

FIX Subsites VirtualPage link to edit main page and TreeDropdownField API implementations

---

.travis.yml
src/Extensions/SiteTreeSubsites.php
tests/php/SiteTreeSubsitesTest.php
tests/php/SubsitesVirtualPageTest.php

Fixes error:
```
Fatal error: Call to a member function get() on null in /path/cwp20rc2/vendor/silverstripe/cms/code/Controllers/CMSMain.php on line 1033
```
I'm expecting this to fail, but will wait to see what else it complains about.
Fixes #351

Use injected CMSMain to prevent unit test error missing dependencies

---

tests/php/SubsiteAdminFunctionalTest.php

This should fix the regressions in SS 4.x-dev where versioned stage params are added to the URL.
see https://github.com/silverstripe/silverstripe-cms/issues/1578

FIX Versioned regressions

---

src/Extensions/SiteTreeSubsites.php

So as to avoid fatal errors while attempting to count.

FIX be consistent with the variable setting

---

code/model/Subsite.php
tests/SiteTreeSubsitesTest.php
tests/SubsiteTest.php

Resolves #252 (for SS3). For SS4 we can modify the logic slightly:
```php
SubsiteState::singleton()->withState(function (SubsiteState $newState) {
$newState->setSubsiteId($this->ID);
DB::quiet();
(new SiteTree)->requireDefaultRecords();
});
```
^ in unit tests and `Subsite::createDefaultPages`.
This will create a home page at least. The logic in `SiteTree::requireDefaultRecords` uses manual SQL queries to determine whether an about us or contact page exist, so that's unlikely to work here. We get a home page at least, which was the original requirement.

FIX Automatically create default SiteTree records for new subsites

---

src/Extensions/LeftAndMainSubsites.php

FIX Double escaping subsites title in CMS menu

---

templates/SilverStripe/Admin/LeftAndMain_Menu.ss

Note that "Main site" is always included in the list of subsites, even though it is not an actual record
Resolves #368

NEW Hide subsite selector dropdown if no subsites have been created yet

---

docs/en/technical.md
javascript/LeftAndMain_Subsites.js
src/Extensions/SiteTreeSubsites.php

A preview link must be loaded on the same domain the CMS is loaded
through, which was previously causing issues when a page (identified
via URLSegment) did not exist on the subsite domain. By _always_
including the identifier in the preview link, this should never happen.
Resolves #263

FIX apply SubsiteID getVar to CMS Preview fetches

---

src/Extensions/SiteTreeSubsites.php

SilverStripe CMS 4.0.0 issues a deprecation notice before calling
alternatePreviewLink on any page that hasMethod (i.e. is applied via an
extension such as SiteTreeSubsites). Instead of double-issuing a notice,
we will just mark this as deprecated in the next minor version via
docblocks.
closes #263 (already resolved via #374)
as per https://github.com/silverstripe/silverstripe-subsites/pull/374#pullrequestreview-134226803

Deprecate alternatePreviewLink function as per CMS

---

.editorconfig
tests/behat/features/preview-navigation.feature
tests/behat/features/publish-a-page.feature
tests/behat/features/select-a-subsite.feature

This adds a new behat test feature for switching between subsites in the CMS, and adds a test that proves the bug in #355 (edit: only in CWP context).
This PR is just adding behat features now

Add subsite switching and page publish behat tests

---

tests/php/SubsiteXHRControllerTest.php

See https://github.com/silverstripe/silverstripe-framework/issues/5594
This was changed in Silverstripe 4.3

Loosen test assertion on content type for application/json

---

src/Extensions/GroupSubsites.php

much better than global state (and should potentially replace cookie usage that is user controlled)

allow using queryParam to disable filter

---

src/Extensions/SiteTreeSubsites.php

API Deprecate duplicateSubsiteRelations. Use "cascade_duplicates" config API instead.

---

src/Extensions/SiteTreeSubsites.php
tests/php/SiteTreeSubsitesTest.php

Resolves #384 
I've removed some of the custom duplication (and legacy) logic and replaced it with some more "core" API calls inside a modified subsite state callback, and have restored the use of `$includeChildren` in recursive duplication of children.
#386 deprecates the `duplicateSubsiteRelations` method since we should now use cascade_duplicates config which will automatically inherit the subsite state now with this PR change (see `onBeforeDuplicate`)

FIX Pages now correctly duplicate children across subsites

---

src/Middleware/InitStateMiddleware.php

This prevents the middleware from interrupting legitimate database exceptions from being propagated.
Fixes #377

FIX Only continue delegation when DB exceptions are caused by no database selected

---

src/Middleware/InitStateMiddleware.php

As per #394 
Change direct call to the AdminRootController config setting, using instead the admin_url() method on the class which provides detection via the Director rules, and the fallback to the config setting.

Change source of admin URL in getIsAdmin()

---

src/Extensions/SiteTreeSubsites.php
tests/php/SiteTreeSubsitesTest.php

Issue: https://github.com/silverstripe/silverstripe-framework/issues/8424

FIX Replace Convert JSON methods with json_* methods, deprecated from SilverStripe 4.4

---

src/Extensions/FolderFormFactoryExtension.php

This will be the default in SilverStripe 4.4, and has been partially implemented in 4.3

NEW Use Bootstrap styled alerts in assets notification

---

.travis.yml
src/Extensions/LeftAndMainSubsites.php
tests/behat/features/insert-content-link.feature

This change allows users with CMSMain permissions to have access in LeftAndMainSubsites::canAccess(), since `ModalController` doesn't define its own permission codes, and usually modals are related to CMS content.
Fixes https://github.com/silverstripe/silverstripe-subsites/issues/357

FIX Content editor group users can now insert links into contents while using subsites

---

lang/en.yml
src/Model/SubsiteDomain.php

Fixes https://github.com/silverstripe/silverstripe-subsites/issues/251 and an issue where the "Mark this as the default domain for this subsite" description was also shown on the protocol option set as well as the "IsPrimary "checkbox

FIX Domains now default to "Automatic" protocol, and have the correct help description

---

src/Pages/SubsitesVirtualPage.php

FIX Field labels for subsites virtual pages are no longer repeated

---

_config/extensions.yml
src/Extensions/HintsCacheKeyExtension.php

Introduces an extension to add the current Subsite ID to the SiteTree Hints Cache Key so that the allowed pagetypes are correctly cached on a per-Subsite basis. Resolves #351.
This patch depends on [an update to the CMS module](https://github.com/silverstripe/silverstripe-cms/pull/2442) that provides this extension point. The code is inert when matched with existing CMS versions.

FIX allowed pagetypes displaying incorrectly when switching subsite

---

docs/en/introduction.md
src/Extensions/SiteTreeSubsites.php
tests/php/SiteTreeSubsitesTest.php

Issue: https://github.com/silverstripe/silverstripe-subsites/issues/416

Ensure URL segment field type before using its API, and add docs around subsite and fluent domain compatibility

---

src/Pages/SubsitesVirtualPage.php
tests/php/SubsitesVirtualPageTest.php

Fixes https://github.com/silverstripe/silverstripe-subsites/issues/423
URLSegment from custom SQL filter was ambiguous, using the ORM fixes this

FIX Subsites virtual pages now allow you to re-save them when used in conjunction with silverstripe-fluent

---

src/Middleware/InitStateMiddleware.php
tests/php/InitStateMiddlewareTest.php

Previously it relied on the PHP-level `$_SERVER` variable; now it will use the `HTTPRequest` so it works correctly in more situations.

Detect domains correctly in Director sub-calls

---

src/Extensions/LeftAndMainSubsites.php
tests/php/LeftAndMainSubsitesTest.php

Access checks are provided with a Member argument, and should revert to using the session member if not provided. The subsites checks were not doing this, despite being provided with a Member argument. This caused an issue with multi-factor authentication where it delays setting the Member to the session until after MFA is verified.
This patch adds handling for a passed Member argument.
Fixes https://github.com/silverstripe/silverstripe-mfa/issues/204

FIX LeftAndMainSubsites::canAccess() now accepts a Member argument and falls back to the session member

---

src/Model/Subsite.php
src/Model/SubsiteDomain.php

Fixes https://github.com/silverstripe/silverstripe-subsites/issues/437
There's no host information available when run from command line because `CLIRequestBuilder` doesn't provide it, so we need to have a fallback to a sensible default.

FIX Prevent undefined index notice when trying to determine HTTP_HOST during dev/build
