silverstripe/silverstripe-subsites

code/SubsitesVirtualPage.php
In SS3.1 we have /admin/pages for cms, was still old link.
=> Wrong edit link in SubsitesVirtualPage

_config/config.yml
Ensure SilverStripe 3.2 compatibility. Fixes #203
=> Added missing route to `SubsiteXHRController`

code/SubsitesVirtualPage.php, javascript/SubsitesTreeDropdownField.js
Replaces https://github.com/silverstripe/silverstripe-subsites/pull/96 (PR against 1.0 instead of master)
=> BUG Subsites selection on SubsitesVirtualPage (fixes #45 and #47)

_config.php, code/SubsiteAdmin.php, code/SubsiteReportWrapper.php, code/SubsiteXHRController.php, code/SubsitesVirtualPage.php, code/extensions/CMSPageAddControllerExtension.php, code/extensions/ControllerSubsites.php, code/extensions/ErrorPageSubsite.php, code/extensions/FileSubsites.php, code/extensions/GroupSubsites.php, code/extensions/LeftAndMainSubsites.php, code/extensions/SiteConfigSubsites.php, code/extensions/SiteTreeSubsites.php, code/extensions/SubsiteMenuExtension.php, code/forms/GridFieldSubsiteDetailForm.php, code/forms/SubsitesTreeDropdownField.php, code/model/Subsite.php, code/model/SubsiteDomain.php, code/tasks/SubsiteCopyPagesTask.php, tests/BaseSubsiteTest.php, tests/FileSubsitesTest.php, tests/GroupSubsitesTest.php, tests/LeftAndMainSubsitesTest.php, tests/SiteConfigSubsitesTest.php, tests/SiteTreeSubsitesTest.php, tests/SubsiteAdminFunctionalTest.php, tests/SubsiteAdminTest.php, tests/SubsiteTest.php, tests/SubsitesVirtualPageTest.php, tests/behat/features/bootstrap/Context/FeatureContext.php
Because @helpfulrobot missed the 1.1 branch
=> Reformat for psr-2

code/extensions/FileSubsites.php
7b11e979fad46e5493ced136749e5620c6d30997 removed by cac77703
=> redoing bugfix 

.travis.yml
I can't see much reason for 1.2 behat tests passing but 1.1 failing, so seeing if this fixes it.
=> Set sudo:false to use new containerised structure

code/extensions/SiteTreeSubsites.php, tests/SiteTreeSubsitesTest.php
Fixes #192
jira ticket at https://silverstripe.atlassian.net/browse/CWP-448
=> BUG Fix copy to subsite breaking on sub-pages

code/extensions/LeftAndMainSubsites.php, code/extensions/SiteTreeSubsites.php, code/tasks/SubsiteCopyPagesTask.php, tests/SiteTreeSubsitesTest.php
=> NEW: Add IncludeChildren option for copying pages between subsites.

code/extensions/SiteTreeSubsites.php
and added some extra methods so it's easier to overwrite or extend
=> made duplication between subsites more robust

code/extensions/SiteTreeSubsites.php
Copying child pages to a subsite is currently broken.
Currently the parent page is copied but not the children. This is because `$this->owner->AllChildren()` is called _before_ `Subsite::changeSubsite($oldSubsite)` which means the children of the _copied_ Page are being returned from `AllChildren()`, and there are none.
Moving `Subsite::changeSubsite($oldSubsite)` up fixes that issue. But then all child pages are copied to the root level. So I've added a param for the parent ID.
=> Fix copying child pages to subsite

composer.json
=> Update PHPUnit version to 4.8

code/extensions/SiteTreeSubsites.php
=> Fix page rendering with proper subsite locale

code/extensions/ErrorPageSubsite.php, tests/php/FileSubsitesTest.php, tests/php/SiteTreeSubsitesTest.php, tests/php/SubsiteTest.php, tests/php/SubsiteTest.yml
=> Sanitise filenames for error pages

code/forms/SubsitesTreeDropdownField.php, code/model/Subsite.php, code/pages/SubsitesVirtualPage.php
=> Add upgrade exclusion rules

.travis.yml, code/extensions/SiteTreeSubsites.php, tests/php/SiteTreeSubsitesTest.php
=> alternateAbsoluteLink() respects action parameter

code/tasks/SubsiteCopyPagesTask.php
=> NEW Add segment to SubsiteCopyPageTask

javascript/LeftAndMain_Subsites.js, src/Extension/SiteTreeSubsites.php, src/Model/Subsite.php
Tidied up the UI, removed custom javascript in favour of core Toggle field.
=> FIX Page type blacklist not matching classes correctly (Fixes 297)

tests/php/SiteTreeSubsitesTest.php
=> update test for handling subsite specific themes

code/model/SubsiteDomain.php
See #327 for previous discussion. Closes #327.
=> Add parent call to onAfterWrite

templates/SilverStripe/Admin/LeftAndMain_Menu.ss
=> Fix alignment of menu toggle icons

_config/extensions.yml
=> FIX Use correct class names for Settings and Subsites admin menu items

src/Extensions/LeftAndMainSubsites.php
=> FIX Redirect user back to the full current URL after changing subsites

.travis.yml, behat.yml, composer.json
=> FIX Re-enable Behat using chromedriver and silverstripe/recipe-testing

src/Extensions/GroupSubsites.php
=> FIX Use correct table name for Group model when performing DB upgrades from older versions

src/Extensions/SiteTreeSubsites.php
Follow up PR from feedback in #369
=> Switch count for exists() check for readability

src/Extensions/FileSubsites.php
It is much better than relying on global state
=> allow disabling filter using queryParam

src/Forms/GridFieldSubsiteDetailFormItemRequest.php
=> FIX Remove duplicate Configuration tabs when creating a new subsite

_config/middleware.yml, src/Tasks/SubsiteMigrateFileTask.php
=> BUG: Fix `MigrateFileTask` not migrating files for subsites

src/Model/Subsite.php, tests/php/SubsiteTest.php
=> FIX Ignore ports when matching domain for subsite

tests/php/SubsiteTest.php
This might help with test state leakage
=> Update testDomainProtocol to use a dataProvider

.travis.yml
See https://github.com/silverstripe/silverstripe-subsites/issues/420
Temporary solution so we can see that the tests are passing
=> Remove code coverage, it is segfaulting on SS 4.4

README.md, src/Extensions/SiteTreeSubsites.php, src/Model/Subsite.php, src/Service/ThemeResolver.php, tests/php/Service/ThemeResolverTest.php, tests/php/SiteTreeSubsitesTest.php
- Fixes an issue where themes would cascade "up" the list of themes
- Provides configuration for defining custom theme options with their own sets of cascading themes
Fixes #392
=> FIX Improving support for cascading themes
